<a href="https://colab.research.google.com/github/bforoura/GenAI/blob/main/Module6/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [1]:
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [2]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [3]:
# Load the full dataset
with open("/content/winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [4]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [5]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [6]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [7]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [8]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [9]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [10]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [11]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [12]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [13]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [14]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [15]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [16]:
example_input_output = train_ds.take(1).get_single_element()

In [17]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,  397,    2, 1559,    2,  119,    2,  182,    9,
        217,    5,  151, 1440,   23,    6,   60,  601,    8,    7, 2835,
        750, 1334,   88,    8,    1, 4499,    3,    5,  161, 1052,    8,
       1343,  853,   32,    6,   28,    3,  185,   83, 1343, 2439,    4,
         15,   18,   21, 1022,    5,  403,   11,  617,   81,  538,  649,
         72,    3,   11,    8, 1734,  219,   19,    6,  396,   31,    4,
         35,   66,    4,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [18]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,  397,    2, 1559,    2,  119,    2,  182,    9,  217,
          5,  151, 1440,   23,    6,   60,  601,    8,    7, 2835,  750,
       1334,   88,    8,    1, 4499,    3,    5,  161, 1052,    8, 1343,
        853,   32,    6,   28,    3,  185,   83, 1343, 2439,    4,   15,
         18,   21, 1022,    5,  403,   11,  617,   81,  538,  649,   72,
          3,   11,    8, 1734,  219,   19,    6,  396,   31,    4,   35,
         66,    4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [19]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [20]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [21]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [22]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [23]:
gpt.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, None)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ token_and_position_embedding         │ (None, None, 256)           │       2,580,480 │
│ (TokenAndPositionEmbedding)          │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ transformer_block (TransformerBlock) │ [(None, None, 256), (None,  │         658,688 │
│                                      │ 2, None, None)]             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, None, 10000)         │       2,570,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,809,168 (22.16 MB)

 Trainable params: 5,809,168 (22.16 MB)

 Non-trainable params: 0 (0.00 B)

In [24]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [25]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [27]:

tensorboard_callback = callbacks.TensorBoard(log_dir="/content/logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [28]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[tensorboard_callback, text_generator],
)

Epoch 1/5
4059/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.5939
generated text:
wine review : us : california : cabernet franc : earthy aromas and charred beef meet stewed grapy aromas on the nose of this bottling . the palate has squeezed red currant , brandied plum , fennel bulb greet the palate , which is extremely showing more restraint . dried herb and tobacco , proving lighter bodied and bright and white pepper alongside black cherry winemaking . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 176s 40ms/step - loss: 2.5938
Epoch 2/5
4058/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.9803
generated text:
wine review : us : california : rosé : cohesive and delicious , this wine is 40 % grenache , 18 % syrah , 7 % syrah and 5 % mourvèdre . if it were sourced on the mountain side of the grape , which is delicious to make for a tempting choice from [UNK] to chicken , or pink . it has quietly might age amidst a backbone of watermelon and cherry cola , with a touch of white

4060/4060 ━━━━━━━━

# 3. Generate text using the Transformer

In [29]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [30]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : oregon : pinot noir : this forward wine ' s light - but tasty , with pretty scents of raspberries , sawdust , cinnamon , orange peel and seductive caramel . 



In [31]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : piedmont : nebbiolo : aromas of underbrush , pressed rose and a whiff of pressed violet lead the nose . the firm palate offers black cherry , star anise , crushed herb and a hint of anise alongside bracing tannins . 



In [32]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : a hint of floral perfume persists throughout this off - dry riesling . it ' s delicately framed with ripe , ripe apple and lime flavors , with a kiss of sweet spice on the finish . 



::   	100.0%
-:   	0.0%
grosso:   	0.0%
blend:   	0.0%
in:   	0.0%
--------



mosel:   	94.6%
rheinhessen:   	2.51%
baden:   	1.52%
rheingau:   	0.96%
pfalz:   	0.2%
--------



::   	99.1%
-:   	0.9%
grosso:   	0.0%
blanc:   	0.0%
in:   	0.0%
--------



riesling:   	99.99%
pinot:   	0.0%
white:   	0.0%
dornfelder:   	0.0%
gewürztraminer:   	0.0%
--------



::   	100.0%
-:   	0.0%
grosso:   	0.0%
blanc:   	0.0%
blend:   	0.0%
--------



a:   	20.23%
while:   	15.8%
whiffs:   	14.56%
dusty:   	9.47%
delicate:   	9.02%
--------



whiff:   	30.82%
hint:   	24.55%
crush:   	10.52%
wisp:   	9.43%
spray:   	9.07%
--------



of:   	100.0%
at:   	0.0%
to:   	0.0%
-:   	0.0%
in:   	0.0%
--------



smoke:   	17.51%
honey:   	16.74%
struck:   	14.46%
petrol:   	14.42%
lanolin:   	11.19%
--------



perfume:   	67.71%
notes:   	11.08%
and:   	7.07%
tones:   	6.46%
,:   	1.85%
--------



persists:   	57.6%
introduces:   	28.14%
lends:   	8.9%
this:   	1.64%
and:   	1.21%
--------



throughout:   	83.6%
on:   	12.38%
through:   	2.04%
from:   	1.82%
,:   	0.09%
--------



this:   	99.95%
the:   	0.03%
,:   	0.02%
fritz:   	0.0%
on:   	0.0%
--------



dry:   	34.24%
intensely:   	9.0%
exceptionally:   	8.98%
delicately:   	6.11%
off:   	5.95%
--------



-:   	99.96%
the:   	0.02%
,:   	0.01%
dry:   	0.01%
a:   	0.0%
--------



dry:   	99.99%
kissed:   	0.0%
[UNK]:   	0.0%
sweet:   	0.0%
gold:   	0.0%
--------



riesling:   	98.61%
,:   	1.34%
white:   	0.01%
wine:   	0.01%
kabinett:   	0.01%
--------



.:   	99.82%
,:   	0.13%
that:   	0.03%
from:   	0.01%
sparkling:   	0.0%
--------



it:   	76.48%
the:   	8.28%
while:   	4.69%
dry:   	0.88%
juicy:   	0.85%
--------



':   	100.0%
is:   	0.0%
balances:   	0.0%
offers:   	0.0%
has:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
09:   	0.0%
11:   	0.0%
--------



lusciously:   	22.48%
a:   	18.7%
delicately:   	16.41%
intensely:   	4.39%
gossamer:   	3.91%
--------



framed:   	88.95%
effervescent:   	5.26%
concentrated:   	2.0%
sweet:   	1.21%
structured:   	0.6%
--------



,:   	84.72%
with:   	11.62%
by:   	2.54%
yet:   	0.55%
in:   	0.33%
--------



a:   	73.05%
notes:   	2.95%
delicate:   	2.76%
bright:   	2.31%
hints:   	2.21%
--------



,:   	32.68%
peach:   	32.43%
yellow:   	8.55%
apple:   	6.51%
tangerine:   	5.86%
--------



sunny:   	50.48%
forward:   	13.74%
sweet:   	7.85%
juicy:   	7.42%
yet:   	3.4%
--------



yellow:   	34.01%
peach:   	29.47%
,:   	7.47%
tangerine:   	7.39%
apple:   	6.78%
--------



and:   	99.22%
,:   	0.67%
flavors:   	0.04%
notes:   	0.04%
-:   	0.01%
--------



pear:   	57.37%
peach:   	15.27%
tangerine:   	6.38%
lemon:   	5.36%
lime:   	4.56%
--------



flavors:   	93.03%
notes:   	5.2%
,:   	0.92%
tones:   	0.24%
-:   	0.19%
--------



.:   	56.89%
,:   	37.31%
that:   	5.49%
accented:   	0.1%
and:   	0.08%
--------



with:   	50.89%
but:   	24.01%
yet:   	10.99%
and:   	6.13%
brightened:   	2.24%
--------



a:   	97.93%
an:   	0.63%
hints:   	0.56%
just:   	0.37%
loads:   	0.09%
--------



hint:   	30.77%
kiss:   	29.6%
touch:   	9.69%
lingering:   	6.14%
brisk:   	3.17%
--------



of:   	100.0%
that:   	0.0%
on:   	0.0%
from:   	0.0%
and:   	0.0%
--------



honey:   	84.05%
sweet:   	13.4%
honeysuckle:   	0.47%
sweetness:   	0.29%
blossom:   	0.2%
--------



,:   	37.84%
honey:   	29.96%
spice:   	13.05%
smoke:   	3.98%
-:   	3.52%
--------



.:   	48.22%
on:   	42.75%
and:   	7.65%
that:   	0.97%
from:   	0.26%
--------



the:   	100.0%
a:   	0.0%
this:   	0.0%
an:   	0.0%
its:   	0.0%
--------



finish:   	87.16%
palate:   	6.6%
midpalate:   	4.45%
nose:   	1.76%
long:   	0.02%
--------



.:   	99.98%
,:   	0.02%
that:   	0.0%
and:   	0.0%
with:   	0.0%
--------



:   	95.37%
drink:   	3.74%
it:   	0.74%
drinks:   	0.09%
the:   	0.02%
--------

